name: WFB-ng package builder for RedHat

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [ 9 ]
        arch: [ "amd64.amd64.max.-mssse3 -mavx -mvzeroupper" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: eval version
        id: get_version
        run: |
            echo "version=rhel${{ matrix.version }}-$(echo "${{ matrix.arch }}" | cut -f1 -d .)" >> $GITHUB_OUTPUT
      - name: build package
        run: |
          curl -s -L https://github.com/svpcom/wfb-ng/releases/download/wifibroadcast-17.10/qemu-7.2.15-fixed.tar.gz | sudo tar xzv -C /
          make rpm_docker CFLAGS="$(echo ${{ matrix.arch }} | cut -f4 -d.)" QEMU_CPU=$(echo ${{ matrix.arch }} | cut -f3 -d.) DOCKER_ARCH=$(echo ${{ matrix.arch }} | cut -f1 -d.) DOCKER_SRC_IMAGE=$(echo ${{ matrix.arch }} | cut -f2 -d.)/rockylinux:${{ matrix.version }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        if: github.event_name != 'pull_request'
        with:
          name: wfb-ng-${{ github.ref_name }}-${{ steps.get_version.outputs.version }}
          path: |
            dist/*.rpm
